---
# theme: jekyll-theme-architect
remote_theme: mdehaas/academic

## Academic theme configuration (https://jekyll-themes.com/academic/) #####
pitch: This is the pitch
# Author
email: info@marceldehaas.com
# curriculum: [optional]
# name: [optional] text of the link. Default : Curriculum Vitae.
# url: [mandatory] url of the curriculum file.
shortbio: Short Bio
author_display: true
# author_website:
twitter_username: marceldehaas
github_username: mdehaas
# linkedin_username:
